name: Continuous Integration

on:
  push:
    branches:
      - '**'
      # - $default-branch
  pull_request:
    branches:
      - '**'
      # - $default-branch

jobs:
  build:
    env:
      COVER: true
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
      id: go

    - name: Get dependencies
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.36.0
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter

    - name: Lint
      run: |
        make lint

    - name: Test
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        ./.github/workflows/test.sh
